#Plugin Made By - Miroshka

# --- Permissions ---
# miroshka.rtp - Access to /rtp command.
# miroshka.rtp.near - Access to teleport near a player. (Requires miroshka.rtp)
# miroshka.rtp.form - Access to the UI form. (Requires miroshka.rtp)
# miroshka.back - Access to /back command.

#------------RTP------------#
# The plugin will search for a safe location until it finds one
# and will preload chunks for smoother teleportation

#Negative And Positive X
x: 1000
#Negative And Positive Z
z: 1000

#------------Teleport Near Player------------#
teleportNearPlayer:
  enabled: true
  # Radius to search for a safe spot around the target player.
  radius: 500

#------------UI Form------------#
# Form UI requires FormConstructor 3.1.0 library: 
# https://github.com/MEFRREEX/FormConstructor/releases/tag/3.1.0
forms:
  enabled: true
  title: "§lСлучайная телепортация"
  content: "Выберите действие:"
  buttons:
    random: "§lТелепортация по миру"
    near: "§lНайти игрока"
  worldSelection:
    title: "§lВыбор мира"
    content: "Выберите мир для телепортации:"
    allowOtherWorlds: true  # Если false, игроки могут телепортироваться только в текущем мире

#---------------------------#

#UnderWaterCheck (Gives Sender Water Breathing If Under Water After RTP) (1 = Enabled) (0 = Disabled)
Watercheck: 1
#Water Breathing Duration In Seconds If Enabled
Duration: 30

#---------------------------#

#RTP Title Message (used when forms are disabled)
Title: §lРандомная телепортация
Subtitle: §lВы телепортированы

#---------------------------#

#Error messages
ErrorMessages:
  NoBackLocation: '§cУ вас нет предыдущего сохраненного местоположения.'
  NoPermission: '§cУ вас нет разрешения на использование этой команды.'
  NotPlayer: '§cЭту команду может использовать только игрок.'
  TeleportFail: "§cНе удалось найти подходящую локацию для телепортации."
  NoPlayersFound: "§cНе найдено других игроков для телепортации."
  WorldNotLoaded: "§cМир, в который вы пытаетесь телепортироваться не загружен"
  InternalError: "§cПроизошла внутренняя ошибка"

#---------------------------#

#Target World Settings
#Set to "" to use player's current world
targetWorldName: ""

# Command settings
commands:
  rtp:
    name: "rtp"
    description: "Random teleportation"
  back:
    description: "Teleport to the previous location."
    usage: "/back"
