name: MultiRTP_MX
version: 1.0.4
author: Miroshka
main: miroshka.MultiRTP
api: [1.0.0]
description: Plugin description here.

commands:
  rtp:
    description: Random teleportation on the map.
    usage: /rtp
  back:
    description: Teleport to the previous location.
    usage: /back

permissions:
  miroshka.rtp:
    description: Allows players to use the command /rtp.
    default: op
  miroshka.back:
    description: Allows players to use the command /back.
    default: op
